name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${GITHUB_REF##*/}.com

    steps:
      - name: deploy
        run: yarn deploy --dir=./app
        env:
          NETLIFY_SITE_ID: c83bedd0-393d-4294-9d43-6dc626cdedf0
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
